---
#temporary folder on target host to unzip the package
temp_folder: "~/tmpa/"

http_port: 8182

#########The following variables shoud be redefined in host_vars
amq_broker_name: amq-a-slave
amq_port: 61617
amq_data_store_folder: ~/nfs/amq-a-store
#this is an example of the list of target brokers
networked_hosts:
  -  connect_to_host: amq-b
     master: amq-b-master
     slave: amq-b-slave
