---
- name: Create Default Users
  lineinfile: 
    dest: "{{target_package_folder}}/etc/users.properties"
    regexp: "^(#?){{ item.value.username }}=(.*)$"
    line: "{{ item.value.username ~ '=' ~ item.value.password ~ ',' ~ item.value.roles | join(',') }}"
    insertbefore: EOF
  with_dict: "{{users}}"

- name: Set Karaf SSH port
  lineinfile: 
    dest: "{{target_package_folder}}/etc/org.apache.karaf.shell.cfg"
    regexp: "^(.*)sshPort(.*)$"
    line: "sshPort = {{karaf_ssh_port}}"

- name: Set Karaf HTTP port
  lineinfile: 
    dest: "{{target_package_folder}}/etc/{{item}}"
    regexp: "^(.*)org.osgi.service.http.port(.*)$"
    line: "org.osgi.service.http.port={{http_port}}"
  with_items: ["org.ops4j.pax.web.cfg","system.properties"]
- name: Set Karaf rmiRegistryPort
  lineinfile: 
    dest: "{{target_package_folder}}/etc/org.apache.karaf.management.cfg"
    regexp: "^(.*)rmiRegistryPort(.*)$"
    line: "rmiRegistryPort={{rmi_registry_port}}"

- name: Set Karaf rmiServerPort
  lineinfile: 
    dest: "{{target_package_folder}}/etc/org.apache.karaf.management.cfg"
    regexp: "^(.*)rmiServerPort(.*)$"
    line: "rmiServerPort={{rmi_server_port}}"

- name: Deactivate AMQ6 Feature
  lineinfile: 
    dest: "{{target_package_folder}}/etc/org.apache.karaf.features.cfg"
    regexp: "^(.*){{item}}(.*)$"
    state: absent
  with_items: ["mq-fabric","camel-amq"]
  when: not setup_amq
