---
- name: Install wildfly Artemis extension
  shell: |
    ./bin/jboss-cli.sh -c --controller=remote+http://{{ansible_ssh_host}}:{{eap_admin_port}} "/extension=org.wildfly.extension.messaging-activemq:add"
  args:
    chdir: "{{ target_package_folder }}"
  ignore_errors: no

- name: Install messaging-activemq subsystem
  shell: |
    ./bin/jboss-cli.sh -c --controller=remote+http://{{ansible_ssh_host}}:{{eap_admin_port}} "/subsystem=messaging-activemq:add"
  args:
    chdir: "{{ target_package_folder }}"
  ignore_errors: no


- name: Install broker config socket bindings
  shell: |
    ./bin/jboss-cli.sh -c --controller=remote+http://{{ansible_ssh_host}}:{{eap_admin_port}} "/socket-binding-group=standard-sockets/remote-destination-outbound-socket-binding=messaging-remote-{{ hostvars[item]['amq_broker_name'] }}:add(host={{ hostvars[item]['ansible_ssh_host'] }},port={{ hostvars[item]['amq_port'] }})"
  args:
    chdir: "{{ target_package_folder }}"
  with_inventory_hostnames:
    - masters
    - slaves
  ignore_errors: no

- name: Install broker config connectors
  shell: |
    ./bin/jboss-cli.sh -c --controller=remote+http://{{ansible_ssh_host}}:{{eap_admin_port}} "/subsystem=messaging-activemq/remote-connector=messaging-remote-{{ hostvars[item]['amq_broker_name'] }}-connector:add(socket-binding=messaging-remote-{{ hostvars[item]['amq_broker_name'] }})"
  args:
    chdir: "{{ target_package_folder }}"
  with_inventory_hostnames:
    - masters
    - slaves
  ignore_errors: no

- name: Create the list
  set_fact:
    connector: "messaging-remote-{{ hostvars[item]['amq_broker_name'] }}-connector"
  with_inventory_hostnames:
    - masters
    - slaves
  register: connectors_list_result

- name: Extract items and turn into a list
  set_fact:
      connectors_list: "{{connectors_list_result.results | map(attribute='ansible_facts.connector') | list}}"

- name: Items to string comma separated
  set_fact:
      connectors_list_string: "{{connectors_list | join(',')}}"


- name: Reload wildfly for Artemis extension
  shell: |
    ./bin/jboss-cli.sh -c --controller=remote+http://{{ansible_ssh_host}}:{{eap_admin_port}} "reload"
  args:
    chdir: "{{ target_package_folder }}"
  ignore_errors: no

#- name: Install broker Pooled JCA Connection 
#  shell: |
#    ./bin/jboss-cli.sh -c --controller=remote+http://{{ansible_ssh_host}}:{{eap_admin_port}} "/subsystem=messaging-activemq/pooled-connection-factory=jms-remote:add(entries=["java:/XaRemoteJmsConnectionFactory"],connectors=[{{connectors_list_string}}],ha=true,user={{ users.admin.username }},password={{ users.admin.password }},client-id={{inventory_hostname}},rebalance-connections=true,allow-local-transactions=true,statistics-enabled=true)"
#  args:
#    chdir: "{{ target_package_folder }}"
#  ignore_errors: no

- name: Install broker Non JCA Connection factory 
  shell: |
    ./bin/jboss-cli.sh -c --controller=remote+http://{{ansible_ssh_host}}:{{eap_admin_port}} "/subsystem=messaging-activemq/connection-factory=simple-jms-remote:add(entries=["java:/JmsConnectionFactory"],connectors=[{{connectors_list_string}}],ha=true)"
  args:
    chdir: "{{ target_package_folder }}"
  ignore_errors: no
