- name: Create the list
  set_fact:
    connector: "messaging-remote-{{ hostvars[item]['amq_broker_name'] }}-connector"
  with_inventory_hostnames:
    - masters
    - slaves
  register: connectors_list_result

- name: Extract items and turn into a list
  set_fact:
      connectors_list: "{{connectors_list_result.results | map(attribute='ansible_facts.connector') | list}}"

- name: Items to string comma separated
  set_fact:
      connectors_list_string: "{{connectors_list | join(',')}}"

- name: Install broker Connection factory non JCA
  shell: |
    ./bin/jboss-cli.sh -c --controller=remote+http://{{ansible_ssh_host}}:{{eap_admin_port}} "/subsystem=messaging-activemq/connection-factory=simple-jms-remote:add(entries=["java:/JmsConnectionFactory"],connectors=[{{connectors_list_string}}])"
  args:
    chdir: "{{ target_package_folder }}"
  ignore_errors: no
