---
#temporary folder on target host to unzip the package
temp_folder: "~/tmpbm/"

http_port: 5182

#########The following variables shoud be redefined in host_vars
amq_broker_name: amq-b-master
amq_port: 51616
amq_data_store_folder: ~/nfs/amq-b-store
