---
- name: Start Fuse instance
  hosts:
    - masters
    - slaves
  tasks:
  - name: start-servers
    include_role:
      name: ansible-role-jboss-fuse-amq-ha
      tasks_from: start-server-artemis

- name: Show admin urls
  hosts: all
  tasks:
  - name: Show urls
    debug:
      msg: "http://{{ansible_ssh_host}}:{{http_port}}/console"
