---
########################################################
#This lists all used variables with their sane defaults

####################################
#### Generic variables
####################################

#flag to say whether to install essential packages on the host such as unzip or java. You could assume the hosts are already installed.
prepare_host: no

#path to the Fuse or A-MQ package
src_package_path: ./../distrib/

#temporary folder on target host to unzip the package
temp_folder: "~/tmp/"

#Fuse or A-MQ package to be installed with version
artifact: amq-broker-7.1.0-bin.zip

#folder on target host 
target_package_folder: "~/broker"

#flag to set whether fuse-karaf server should be configured on the the host
setup_karaf: no

http_port: 8181

#setup default users
users:
  admin:
    username: admin
    password: admin
    roles:
      - admin
      - manager
      - viewer
      - Monitor
      - Operator
      - Maintainer
      - Deployer
      - Auditor
      - Administrator
      - SuperUser
  deployer:
    username: deployer
    password: deployer
    roles:
      - Deployer
  guest:
    username: guest
    password: guest
    roles:
      - viewer

####################################
#### AMQ 6 & 7 variables
####################################

#flag to choose whether to setup A-MQ 6 brokers
setup_amq: no

#flag to choose whether to setup a network of AMQ brokers
setup_amq_network: no

#########The following variables shoud be redefined in host_vars
amq_broker_name: amq
amq_port: 61616
amq_data_store_folder: ~/amqdata
#this is an example of the list of target brokers
networked_hosts:
  -  connect_to_host: amq-b
     master: amq-b-master
     slave: amq-b-slave

# AMQ 7 artemis specific vars
setup_artemis : yes