---
########################################################
#This lists all used variables with their sane defaults

####################################
#### Generic variables
####################################

#flag to say whether to install essential packages on the host such as unzip or java. You could assume the hosts are already installed.
prepare_host: no

#temporary folder on target host to unzip the package
temp_folder: "~/tmpfuse/"

#Fuse or A-MQ package to be installed with version
artifact: jboss-eap-7.2.0.zip

#folder on target host 
target_package_folder: "/home/workdrive/apps/EAP-FUSE/fuse"

#flag to set whether fuse-karaf server should be configured on the the host
setup_karaf: no
setup_eap : yes
setup_eap_cluster : yes

http_port: 8080
https_port: 8443

eap_admin_port : 9990

# patching before isntall of Fuse
eap_patch_list: 
  - jboss-eap-7.2.1-patch.zip

# patching after installation of Fuse
eap_patch_list_after_fuse:
  - jboss-eap-7.2.4-patch.zip
  - jbeap-17583.zip
  - jbeap-17715.zip

eap_fuse_installer: fuse-eap-installer-7.4.0.jar

####################################
#### A-MQ 6 variables
####################################

#flag to choose whether to setup A-MQ 6 brokers
setup_amq: no

#flag to choose whether to setup a network of A-MQ 6 brokers
setup_amq_network: no

# AMQ 7 artemis specific vars
setup_artemis : no

####################################
#### Prometheus variables
####################################

prom_config: prometheus-camel-config.yml